### ISSUE TITLE
Add user login component

### ISSUE THREAD

**Issue by esscott** [Smithsonian/ForestGEO#45]
As a principal investigator for a research site, I want each member of my team to be required to login to the ForestGEO App with a unique user identity, so that multiple people can use app at the same time, and their user data is automatically attached to each submission of new census data.

**Comment by Jaro05** [comment]
Login button in upper right corner.
Clicking this links to new page on the app to login.
Enter email, and password.
Validate email and password and display correct Error messages.
After validation, brief "Login completed" screen.
Return to home page of app.
Now there is a profile icon in the top right instead of login button, with ability to sign out!
Sign out/profile functionality should be a separate issue.

^This is the workflow I was thinking for the log in component. Is there anything else that needs to be added?

**Comment by Jaro05** [comment]
This issue has been resolved. The login component still has minor work to be done, but it has been merged with main.
