### ISSUE TITLE
TypeScript configuration is set for es5 JS standard

### ISSUE THREAD

**Issue by zmagar** [Smithsonian/ForestGEO#64]
Is there any particular reason to have target parameter set to es5? It doesn't support arrow functions so TS compiler will translate them into traditional ones, etc. ES6 revision is supported by all modern browsers for the last 5-6 years. I understand that some remote sites can have very old PCs with IE11 or something, is this a concern, @esscott?

**Comment by esscott** [comment]
@zmagar I'm sorry I missed this. Does this question still need answering?

**Comment by zmagar** [comment]
@esscott And I missed your answer! It's not very important question and it seems like --target parameter doesn't do much except for rewriting syntax.

**Comment by illume** [comment]
Probably this was a default made by the create-react-app typescript template. 

So far we only support modern browsers based on using Mui 5, which includes IE 11 with partial support. https://mui.com/material-ui/getting-started/supported-platforms/
![image](https://user-images.githubusercontent.com/9541/187954502-45bbd0c9-52d1-4be7-824f-1054fc156795.png)

Unless there's a good benefit for changing it, then I'd suggest we keep it as is. Because perhaps IE11 will be important to support in the future.

I'll close this, since it seems it's not a concern for zmagar anymore.


(as always; feel free to reopen if needed)
